### ISSUE TITLE
Bug: Dates of orders not showing

### ISSUE THREAD

**Issue by StanislavJochman** [kudlav/kam-vutbr#7]
Hi, I have noticed that the dates of food orders are no longer showing as can be seen on the screenshot. I am running Pixel 6 with Android 14.
![Screenshot_20231009-113523](https://github.com/kudlav/kam-vutbr/assets/27728863/df8b78c4-8a83-424f-83a9-ca1fd45feee8)

**Comment by kudlav** [comment]
Should be fixed in v1.7.0 by a062b02

**Comment by StanislavJochman** [comment]
Thanks

**Comment by kudlav** [comment]
Version 1.7.0 should be available for everyone on Google Play.
